### ISSUE TITLE
On Windows, TeX->MML, inline-math delimiters coming through as mo's

### ISSUE THREAD

**Issue by cxw42** [mathjax/MathJax-node#120]
Summary: `tex2mml "$x=42$"` adds a `$` to the start of the output, but MathJax 2.5.3 doesn't.

Environment: Windows 7, 64-bit, running 32-bit node.js 0.12.7 and MathJax-node 0.3.0 (including MathJax 2.5.1).

To reproduce: from the Node.js command prompt, run `node tex2mml "$x=42$"`

Output: 
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mrow class="MJX-TeXAtom-ORD">
    <mo>$</mo>
  </mrow>
  <mi>x</mi>
  <mo>=</mo>
  <mn>42</mn>
</math>
```

The `<mrow>` and `<mo>$</mo>` shouldn't be there.  Expected output:

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mi>x</mi>
  <mo>=</mo>
  <mn>42</mn>
</math>
```

I can get the expected output by:
 * omitting the `$ $`: `node tex2mml "x=42"`.  
 * adding `--inline`: `node tex2mml --inline "$x=42$"`
   * However, `--inline` isn't a panacea - the extra `$` still appears with `node tex2mml --inline "$$x=42$$"`, and I am hoping to be able to bulk-convert equations without having to manually flag them as inline or display.  
   * Also, `node tex2mml "$$x=42$$"` gives `<math xmlns="http://www.w3.org/1998/Math/MathML" display="block" />`

I am reporting this since the MathJax 2.5.3 sample in https://github.com/mathjax/MathJax/blob/master/test/sample-dynamic-2.html correctly processes math including the `$ $` (or `$$ $$`), providing the expected output above for `$x=42$` (and correct output for `$$x=42$$`).  I have checked the release information for 2.5.2 and 2.5.3 and I can't see anything suggesting this is an upstream issue that will go away when MathJax-node moves to MathJax 2.5.3.  However, if it's a configuration option or something simple I'm missing, please let me know and close this out!  

I did look at sample-dynamic-2.  I noticed it refers to `?config=TeX-AMS-MML_HTMLorMML`, which loads a number of extra extensions.  Based on that list, I tried `node tex2mml --extensions MathEvents,TeX/noErrors,TeX/noUndefined,TeX/AMSmath,TeX/AMSsymbols "$x=42$"` but got the same result.

Thank you!

**Comment by dpvc** [comment]
All of this actually is correct behavior.  The main issue is that you are *not* supposed to include delimiters in the math you send to `tex2mml` or any of the other single-expression processors.  The output style is controlled by the `--inline` option, not delimiters in the math string.

The way it works is that `tex2mml` adds `$...$` around the math when `--inline` is present, and `$$...$$` when it isn't.  So your example of `node tex2mml --inline "$x=42$"` causes MathJax to see `$$x=42$$`, which is typeset as display-mode mathematics (with `display="block"), while `node tex2mml "$x=42$"` causes MathJax to see `$$$x=52$$$`, which it inter presets as `$$ followed by `$x=42` followed by the closing `$$`, followed by an unmatched `$`.  So it typesets `$x=42`, giving you the initial dollar sign that you see in your output.

Similarly, `node tex2mml "$$x=42$$"` causes MathJax to see `$$$$x=42$$$$`, so the two initial `$$` match the second `$$`, producing an empty pair of math delimiters, and the result is an empty math block, as you found.  the `x=42` is outside of the math, and is followed by a second set of empty math delimiters.

The [sample-dynamic-2](https://github.com/mathjax/MathJax/blob/master/test/sample-dynamic-2.html) file that you cite operates completely differently, as it processes paragraphs containing math, not just a single expression, as `tex2mml` does.  The more [sample-dynamic](https://github.com/mathjax/MathJax/blob/master/test/sample-dynamic.html) example is more in line with how `tex2mml` works.

There are several approaches you could take to do what you want.  First, the code that you are using to extract the math from wherever you have it stored could strip the delimiters and insert the `--inline` option when the delimiters were `$...$`.  If that isn't possible, you could make a copy of `tex2mml` and modify it to detect and remove the delimiters for you (and set the value used by `--inline` appropriately).  Of course, running `tex2mml` for each equation is a very inefficient approach, as it would have to load an initialize MathJax for each expression.  A better approach would be to put all your expressions into one file and use `page2mml` to process them all at once (or at least in larger blocks of equations).  Or you could use `tex2svg-filter` as a model and make a version that does conversion to mml rather than SVG.  The `tex2svg-filter` command takes multiple expressions (with delimiters) and converts them to SVG storing the results in files.  You could change that to produce MathML output and either store it in files or just print the output (where you could break it up into its individual expressions again by matching `<math>` and `</math>` delimiters).

**Comment by cxw42** [comment]
@dpvc Thanks very much for the detailed answer!  I greatly appreciate it.
