### ISSUE TITLE
Add option to disable html reformatting

### ISSUE THREAD

**Issue by andya9** [mathjax/MathJax-node#124]
When running page2mml on a html document the markup gets messed up: the main problem is with code elements inside pre elements: the code is squashed into a single line messing up its rendering. Also, I noticed that if anchor.js is linked inside the html, the elements it should create client-side are created from Mathjax server-side.
Is it intended? is there an option to only process math elements? I already use it with "--format AsciiMath" option

**Comment by pkra** [comment]
> When running page2mml on a html document the markup gets messed up: 

Could you share a minimal example?

Does this happen in a page without mathematics? It sounds more like a jsdom issue as MathJax does not touch non-math content.

> if anchor.js is linked inside the html, the elements it should create client-side are created from Mathjax server-side.

This should not happen when jsdom is configured correctly, i.e., via https://github.com/mathjax/MathJax-node/blob/master/bin/page2mml#L91.

**Comment by dpvc** [comment]
> This should not happen when jsdom is configured correctly

It is probably happening when the content is inserted into the DOM in the `lib/mj-page.js` file, since scripts are enabled there (so that MathJax itself will run).  The library should probably remove scripts from the page so that they don't run, and then put them back before returning the results.

> the main problem is with code elements inside pre elements: the code is squashed into a single line

I am not able to reproduce the problem.  The formatting inside `pre` elements seems to be preserved for me (the newline directly following the `<pre>` is removed, but that is redundant anyway, and doesn't affect the output).

In any case, Peter is correct that this would be a `jsdom` bug.

**Comment by andya9** [comment]
Thank’you very much for looking into this. 
Now everything seems fine: I reinstalled node and all local packages; also, I switched from node 0.12 to 4.1.2 and installed mathjax from develop. I don’t know what got wrong, but it seems to be fixed.
Thank’you again!
