### ISSUE TITLE
Update mathjax reference

### ISSUE THREAD

**Issue by physikerwelt** [mathjax/MathJax-node#131]
In https://phabricator.wikimedia.org/T106890 we discoverd that the mathjax branch https://github.com/mathjax/MathJax/tarball/mathjax-node-2.5.1 seems to be outdated. Especially it does not handle smallmatrix like http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic.html 
cf. https://github.com/physikerwelt/MathJax-node/commit/d748790fdf042be3a55bdd0972dd72565ffe1c76#diff-c2c2cec06b7adf3e5bce040316346d45R16

**Comment by dpvc** [comment]
The changes between 2.5.1 and 2.5.3 are basically irrelevant to MathJax-node, so we didn't do an updated branch for that.  There is a small change to how \mathchoice is handled, and slightly better handling of math inside `\text{}`.

As for `smallmatrix`, v2.5.1 handles that just fine; you test file however does not detect it properly.  It seems to be looking for a `scriptlevel` attribute, but `smallmatrix` doesn't produce one.  The reason that there is one in the output of `sample-dynamic.html` is that that HTML file puts `\displaystyle{...}` around the mathematics that you type, and that is what generates the `mstyle` with the `scriptlevel`.  So you are testing for something that does not come from the `smallmatrix` environment.

**Comment by physikerwelt** [comment]
@dpvc Thanks I missed the displaystyle which the math extension would use as well.
I'm now convinced that scriptlevel=0 is the better than scriptlevel=1
However, the main problem here is that Firefox has too much space between the rows.
![screenshot 2015-11-01 20 11 17](https://cloud.githubusercontent.com/assets/2777736/10870826/f5895dd2-80d4-11e5-9483-ba27bc6a8b69.png)
![screenshot 2015-11-01 20 10 53](https://cloud.githubusercontent.com/assets/2777736/10870827/fa665f94-80d4-11e5-830b-0c8a51b027ca.png)

**Comment by dpvc** [comment]
I checked into it a little further, and MathJax does have a problem with the MathML that it produces for `smallmatrix` (though it is not the problem that Fred referred to with the handling of `scriptlevel` in `mtable`, which was fixed at the time the issue was clarified by the Math WG).  It turns out that MathJax marks the array to use a `scriptlevel` of 1, and that is what is being used by the HTML-CSS and SVG renderers, but that `scriptlevel` is not being included in the MathML output.

As for the wide lines, I think Fred identified a CSS issue in the tracker item you link to above.  It appears that the `line-height:1.6` setting is the source of the problem.  You may need to add more CSS to override that for the math blocks.  Setting it to `1.2em` or even `1em` might do the trick.

**Comment by pkra** [comment]
Resolved upstream.
