### ISSUE TITLE
add support for browserify [was: browserify build fails]

### ISSUE THREAD

**Issue by Ledokol** [mathjax/MathJax-node#147]
I'm trying to build mathjax-node to bundle with browserify.

main.js file:

```
var mjAPI = require('mathjax-node')
```

Regular node execution works fine

```
$ node main.js 
```

But browserify returns error

```
$ browserify main.js --node
Error: Cannot find module 'canvas' from 'path/mj/node_modules/jsdom/lib/jsdom/level2'
```

How to fix this?

**Comment by pkra** [comment]
Right now, mathjax-node is not (yet) compatible with browserify (webpack etc). Primarily, that's because the underlying core MathJax library is not compatible (though jsdom itself I think is nowadays). 

FWIW, I once tried to hack something together using a custom single-file build for MathJax but ran into trouble loading that into jsdom in the browserified result; someone more knowledgeable about jsdom and browserify might get that to work.

**Comment by bhargavdt3** [comment]
Did the issue if build with Webpack is solved ?

**Comment by VernonGrant** [comment]
👍 Would be nice...

**Comment by lukeburns** [comment]
👍

**Comment by pkra** [comment]
Closing this here. MathJax v3 can be used with browserify and will subsume mathjax-node; cf.  #375.

**Comment by ccravens** [comment]
@pkra thank you for the update on this. I'm looking to use MathJax with browserify bundling for a presentation that will most likely be offline in a few weeks. Will the v3 be released and available via the npm repo anytime soon? (https://www.npmjs.com/package/mathjax) Thank you!

**Comment by pkra** [comment]
@ccravens see https://groups.google.com/forum/#!topic/mathjax-dev/Pw3ibW0nWFY for details, incl the alpha's npm package.
