### ISSUE TITLE
How can i use it  in React Native

### ISSUE THREAD

**Issue by DavyLin** [mathjax/MathJax-node#148]
I use the lib in React Native.
      var mjAPI = require('mathjax-node');
 error message :
      Unable to resolve module child_process from /Volumes/hdd/work/react-projects/mathDemo/node_modules/mathjax-node/lib/mj-page.js:Invalid directory /Volumes/node_modules/child_process
 
help!

**Comment by pkra** [comment]
You might want to add a complete minimal example. It would also help to add links about what react native requires from Node modules. Finally, you might want to check if upstream libraries that we use are compatible, e.g., jsdom.

**Comment by MeKarina** [comment]
the problem is.. react native doesnt support node core module.. all npm module that depend on node core module arent compatible with react native... but compile version should work with react native

@pkra have plan to provide compile version..??

**Comment by pkra** [comment]
I suspect the main point of confusion is client vs server-side rendering. 

MathJax-node is limited to a server-side rendering. It can be integrated into server-side react rendering, see for example https://github.com/mathjax/MathJax-node/issues/146. 

While it's conceivable that you could hack together a modification of mathjax-node that runs on the client, we suggest to use (core) MathJax itself for that (for one, you would not want to load jsdom on the client where you have much faster DOM implementation at hand). 

Unfortunately, MathJax does not integrate into client-side react workflows well at this time; it requires content in the DOM for rendering.

However, the necessary changes that would enable in MathJax's core are planned for MathJax v3.0 next year. Very likely, v3.0 will simply make mathjax-node obsolete -- core MathJax should run in both client and server settings and be able to avoid DOM interactions. You can follow the discussions around v3.0 on our [development mailing list](https://groups.google.com/forum/#!forum/mathjax-dev).

**Comment by MeKarina** [comment]
yep mathjax core indeed work with react native webview https://facebook.github.io/react-native/docs/webview.html ...

but that kind inefficient and not flexible because it is intended to render a website... so im looking for latex that generate svg output n stumble to this library...

but so glad to hear mathjax 3 will support browserless environment... looking forward for mathjax 3...

**Comment by pkra** [comment]
Ah, sorry. I was forgetting this issue was about react native. 

In the context of react native (if you can't use a webview), then it would make sense to ship a copy of mathjax-node (with jsdom since you do not have a DOM available). 

I haven't tested it but one approach might be to use browserify to wrap mathjax-node together (since browserify can wrap jsdom). However, this would require at least a couple of hacks of mathjax-node and it's only the first step; personally, I simply haven't had a project that provided sufficient motivation (with v3 now leaving the design phase).
