### ISSUE TITLE
Cannot find module 'cssstyle/lib/parsers.js'

### ISSUE THREAD

**Issue by a3nm** [mathjax/MathJax-node#179]
Hi,

I tried to install mathjax-node on a fresh Debian testing install as follows:

```
# nodejs-legacy required for node to be available as "node" rather than "nodejs"
apt-get install npm nodejs-legacy
npm install mathjax-node
```

I then tried to run:

```
node_modules/mathjax-node/bin/am2html
```

It results in the following:

```
module.js:328
    throw err;
    ^

Error: Cannot find module 'cssstyle/lib/parsers.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /node_modules/mathjax-node/lib/patch/jsdom.js:51:17
    at Object.<anonymous> (/node_modules/mathjax-node/lib/patch/jsdom.js:94:3)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

It seems that this problem can be fixed by issuing:

```
npm install cssstyle
```

Is this because the dependency of "mathjax-node" on "cssstyle" is not declared?

**Comment by dpvc** [comment]
Can you say what versions of `node` and `npm` you are using?  (Use `node --version` and `npm --version`.)

> Is this because the dependency of "mathjax-node" on "cssstyle" is not declared?

No, `cssstyle` is not a dependency of `mathjax-node`, it is a dependency of `jsdom`, which is a dependency of `mathjax-node`.  But it has some bugs, and `mathjax-node` tries to patch those.  There was a change in the directory structure used by `node` between versions 4 and 5, and so `mathjax-node` has some logic to try to locate the library in both possible hierarchies.  Apparently, this isn't working properly.  Can you do `find . -name "cssstyle"` within the `mathjax-node` directory and tell me where the `cssstyle` library has been located in your case?  (Since you installed it explicitly yourself, there may be two copies.)

**Comment by dpvc** [comment]
I believe that I have located the issue.  It is the same one described in PR #172.  The `issue172` branch includes a patch.  You can make the corresponding changes to your copy of `mathjax-node/lib/patch/jsdom.js` and that should resolve the issue for you.

**Comment by a3nm** [comment]
Thanks for your answer! Here are the versions (they are the ones packaged by Debian testing):

```
$ node --version
v4.3.0
$ npm --version
1.4.21
```

I confirm that I can fix the problem by applying the patch of branch `issue172` instead of doing a fresh install of `cssstyle`.

So I think this issue will just be fixed whenever the patch of `issue172` is merged.

Thanks again!

**Comment by dpvc** [comment]
Great!  Thanks for the confirmation.
