### ISSUE TITLE
The intergral symbal is abnormally small in inline-Tex to SVG mode

### ISSUE THREAD

**Issue by tuananhtd** [mathjax/MathJax-node#195]
This is the my piece of code to testing the inline-Tex to SVG feature.

```
var fs = require("fs");
var mjAPI = require("mathjax-node/lib/mj-single.js");
mjAPI.config({
  MathJax: {
  }
});
mjAPI.start();

var yourMath = '\\int_{1}^{2}{\\dfrac{a^2}{b}}';

mjAPI.typeset({
  math: yourMath,
  format: "inline-TeX", // "inline-TeX", "MathML"
  svg: true,
}, function (data) {
  if (!data.errors) {
    fs.writeFileSync('index.html', "<!DOCTYPE html>\n<html>\n<head>");
    fs.appendFileSync('index.html', '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />');
    fs.appendFileSync('index.html', "<title></title>\n<style>");
    fs.appendFileSync('index.html', "</style>\n</head>\n<body>");
    fs.appendFileSync('index.html', data.svg);
    fs.appendFileSync('index.html', "</body>\n</html>");
  }
  else {
    console.log(data.errors);
  }
});
```

However the integral symbol seem to be incorrectly rendered. It's too small (check the pic below).
![image](https://cloud.githubusercontent.com/assets/14288059/13724400/fbd40e7c-e8b6-11e5-9b5f-6848318abfef.png)
I tried the same thing with mathML to SVG and the math was rendered beautifully as it should be.
Could this be an issue? or am I missing something?
Thanks!

**Comment by dpvc** [comment]
The output is correct.  In TeX, an inline integral is always that size, and a display-style integral is always the larger integral.  It doesn't matter what the contents of the integral is.

You have not given the MathML that you used, but I suspect you had `display="block"` on the `<math>` element, or an `<mstyle displaystyle="true">` surrounding it.  But

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <msubsup>
    <mo>&#x222B;<!-- ∫ --></mo>
    <mn>1</mn>
    <mn>2</mn>
  </msubsup>
  <mrow>
    <mstyle displaystyle="true" scriptlevel="0">
      <mfrac>
        <msup>
          <mi>a</mi>
          <mn>2</mn>
        </msup>
        <mi>b</mi>
      </mfrac>
    </mstyle>
  </mrow>
</math>
```
displays as in your picture above.

If you want to force a larger integral, then use `\\displaystyle\\int_{1}^{2}{\\dfrac{a^2}{b}}`, or use `format: "TeX"` rather than `format: "inline-TeX"`.  The output you received is the output that you have asked for in this case.

**Comment by tuananhtd** [comment]
Thank you @dpvc !

**Comment by saivan** [comment]
I'm sorry to comment on a closed issue, but I'm just comparing the output on the mathjax site:

![image](https://user-images.githubusercontent.com/8543370/31533468-b8127c62-b035-11e7-9dbf-52c4231c844c.png)

To what I get when I typeset the string:

```
\int_D \left( \nabla \cdot F \right) dV = \int_{\partial D} F \cdot n dS
```

Which is:

![image](https://user-images.githubusercontent.com/8543370/31533508-fcb336a4-b035-11e7-86d0-7fbbf70bd180.png)

I'm using the tex mode (not tex inline), shouldn't this be using display math?
It still looks rather different.
