### ISSUE TITLE
mathML double-struck lowercase letters render as normal in SVG output

### ISSUE THREAD

**Issue by corinnaSchultz** [mathjax/MathJax-node#200]
I took the sample mathML from the following url and saw that double-struck (as well as script and bold-script) lowercase letters were being rendered as "normal" -- except for a double-struck lowercase k.

     https://www.dessci.com/en/reference/mathmltestsuite/testsuite/Presentation/TokenElements/mi/mimathvariant14.html

Snippet screenshot illustrating the unexpected output: 

<img width="210" alt="lower_case" src="https://cloud.githubusercontent.com/assets/8988264/13969384/bf87f196-f03f-11e5-86f9-040e463110c2.png">

I would expect an output similar to the characters shown in this table:

     https://www.w3.org/TR/MathML2/double-struck.html

This is my mathJax config:

     mathJaxApi.config({
     MathJax: {
        SVG: {
            font: "TeX"
        },
        styles: {
            '.mfrac': {
                'font-size': '92.1%'
            }
        }
     }
     });

**Comment by dpvc** [comment]
The MathJax TeX fonts that you have selected don't contain lower-case double-struck or script characters, so these variants will not render the lower-case characters.  Also, the MathJax TeX fonts don't include bold-script at all (you can see that the upper-case characters in both of those versions are the same).

The MathML spec makes it clear that renders are not requires to have every character in every variant, and that renders may produce different results for such things.  The MathJax fonts are relatively small (so that they load quickly as web fonts), and so not every character is available in all variants.  If you want greater coverage, then you might try the STIX fonts, which have fuller coverage of the math alphabets.

**Comment by dpvc** [comment]
PS, the lower-case double-struck K happens to be in the AMS fonts on which the MathJax TeX fonts are based, which is why that one letter is available but no others.
