### ISSUE TITLE
[mj-single] [CHTML] critical css

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#218]
Here's a question.

IIUC we're adding the complete stylesheet to `data.css`. It would be convenient to generate critical css, i.e., the minimal stylesheet necessary for an equation (cf. somewhat how SVG paths are handled). 

However, I'm not sure if this is an upstream issue, i.e., if core MathJax currently provides any facilities for this.  Perhaps we should leave critical css shenanigans outside of mathjax-node as well?

**Comment by dpvc** [comment]
I don't think it is an upstream issue, as it would complicate and slow down the CommonHTML output jax to do that in MathJax itself.  For every element added to the page, MathJax would need to check if the CSS for it has been added already, and if not add it.  I'm not sure what the overhead would be, but it is more than what is currently done.  You would want to add the new CSS to an existing style sheet, but MathJax currently doesn't have facilities for that (only for making new style sheets), and you might need to group the additions to avoid reflows (I haven't checked to see the impact of changing stylesheets on the fly).

I think it is probably a post-processing step, but the interconnections are complicated, and even that would need to be handled pretty carefully.  I suppose one could run through the list of keys for the styles and use `querySelector()` to see if any elements match, and discard if not.  The `@font-face` directives would be a bit harder, since they are interconnected in a way that is non-trivial to unwind.

**Comment by pkra** [comment]
>  it would complicate and slow down the CommonHTML output jax to do that in MathJax itself. 

Thanks for clarifying.

> I think it is probably a post-processing step, but the interconnections are complicated, and even that would need to be handled pretty carefully.

I agree. There are [many tools](https://www.npmjs.com/search?q=critical%20css) out there to deal with critical CSS so I think we can leave that to the user.
