### ISSUE TITLE
state.ID does not increment

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#260]
This is because the state is update in `TypesetDone` before `GetSVG` runs (to increment it).

Relates to #207.

**Comment by pkra** [comment]
Simple fix is to change state in `GetSVG` but again #207.

**Comment by dpvc** [comment]
The problem was caused by commit 95644e79 that broke `TypesetDone()` into two parts, and moved the `TypesetDone()` call to before the rest of the routines (including `GetSVG()`).  I think the solution is to move the saving of the `state` to the final routine, `ReturnResult()`, like it was originally  so that it is done after the increments.  Saving the state can certainly be considered part of returning the result, after all.

**Comment by pkra** [comment]
Copy that. Will probably have time when I'm back from TPAC.
