### ISSUE TITLE
[SVG output] mglyph issues

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#263]
Something like 

```html
<math> <mi><mglyph src="my-glyph.png" alt="my glyph"/></mi> </math>
```

becomes

```html
<svg xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0.343ex" style="vertical-align: -0.171ex;" viewBox="0 -73.8 0 147.5" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg">
<defs></defs>
<g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)">
 <image src="my-glyph.png" alt="my glyph" title="my glyph" y="0" height="0" width="0" transform="translate(0,0) matrix(1 0 0 -1 0 0)" preserveAspectRatio="none" xlink:href="file://my-glyph.png/"></image>
</g>
</svg>
```

Besides (invalid?) `src` attribute, the `xlink:href` gets a `file://` prefix which is not ideal.

This might be an upstream issue with jsdom or MathJax.

**Comment by pkra** [comment]
For comparison, Common HTML output stays relative:

```html
<span class="mjx-chtml"><span class="mjx-math" role="math"><span class="mjx-mrow"><span class="mjx-mi"><span class="mjx-mglyph"><img src="//my-glyph.png" alt="my glyph" title="my glyph" style="vertical-align: 0;"></span></span></span></span></span>
```

**Comment by dpvc** [comment]
The `src` attribute was removed in [this commit](https://github.com/mathjax/MathJax/commit/02cfa458d8891dc88246b14ea5e01742bf4b41aa), so the is taken care of already in the develop branch.  The `file://` is coming from the fact that the SVG mglyph implementation creates an Image object to load the image (to get its size), and it uses that object's `src` attribute for the `xlink:href` rather than the original mglyph `src`.  That is supposed to be a full URI, and so in jsdom, that becomes `file://...`.  I suppose the mglyph could use the original `src` attribute instead.  This would be most easily handled in MathJax rather than MathJax-node.  Should I make the change upstream for v2.7?

**Comment by pkra** [comment]
> The src attribute was removed in this commit, so the is taken care of already in the develop branch

I'm still seeing a src attribute using develop. I'll check it out.

> This would be most easily handled in MathJax rather than MathJax-node. Should I make the change upstream for v2.7?

Sound good to me.

**Comment by dpvc** [comment]
I have made a [commit](https://github.com/mathjax/MathJax/commit/2d9cd83fe6960cbac3d3707c5ce9c9f1ef11956b) in MathJax that fixes this problem.

**Comment by pkra** [comment]
Fixed upstream.
