### ISSUE TITLE
configure jsdom to block remote resources

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#279]
From the discussion of [#134](https://github.com/mathjax/MathJax-node/issues/134#issuecomment-261920746), we currently do not [prevent remote resources](https://github.com/tmpvar/jsdom#external-resources) from being loaded into the jsdom window (e.g., via the MathJax configuration) this is [a security risk](https://github.com/tmpvar/jsdom#on-running-scripts-and-being-safe).

**Comment by dpvc** [comment]
I understand the concern, but in the current (develop) branch, since we are not processing arbitrary HTML from the user, there is no real issue.  The math content from the user is inserted as text (not HTML) into a MathJax script tag, so it is not possible for this to cause arbitrary code execution.  Loading of code by MathJax via extensions only comes from the MathJax extensions directory or from the `Contrib` directory.

Do you have a particular security issue in mind?

**Comment by pkra** [comment]
> Do you have a particular security issue in mind?

We do not take responsibility for any code in the third party extension repository and we do not review it in general. The browser sandbox gives us a lot of safety on the client but jsdom is much less secure. For me, this is a no-brainer. 

I think we definitely need an option to disable it, e.g., for people that provide mathjax-node as a public service (e.g., wikimedia). But I would strongly favor making blockingn the default; people can still disable it should they want to take on the risk to their systems.

**Comment by dpvc** [comment]
> We do not take responsibility for any code in the third party extension repository and we do not review it in general.

Note that that is true whether they load the code from the CDN or install it locally and run it from there.  Code from the `[Contrib]` directory is only loaded in response to an extension being included in the MathJax configuration (not by math that is processed by MathJax).  So running that code would only happen if the node application author specifically requested it.  Running a web service does not change the fact that the only code execution that processing a math expression can cause is the loading of extensions from the MathJax extensions directory.

Because MathJax itself needs to be able to load and run, `FetchExternalResources` and `ProcessExternalResources` both have to include `"script"`, otherwise MathJax will not run.  So that leave only filtering out the non-MathJax resources (functionality that I don't think existed in jsdom when mathjax-node was originally written).  You might be able to use `SkipExternalResources` to do that by setting it to something like `/https?:\/\/.*/` but that would only prevent network-based loading.  It would probably be better to use a custom resource loader, which is much more complicated, but the only other option.  

Note that people worried about this could use `require("jsdom").defaultDocumentFeatures` to install their own resource loader or `SkipExternalResources`.

> people can still disable it should they want to take on the risk to their systems.

I still do not understand the risk that you are suggesting, as I do not see a means for the mathematical expressions to cause arbitrary script execution (and if there were, it would be a problem for MathJax itself, not just mathjax-node); all other code run by mathjax-node is at the request of the person running the node application, even if they are running a web service.

**Comment by pkra** [comment]
>  So running that code would only happen if the node application author specifically requested it.

I was thinking of a web service that allows users to send a configuration as well (e.g., to handle different math delimiters). In that situation, I would see a risk. Am I wrong in thinking that?

> You might be able to use `SkipExternalResources` to do that by setting it to something like `/https?:\/\/.*/` but that would only prevent network-based loading. 

That was what I was thinking about. Maybe that's too simplistic.

> if there were, it would be a problem for MathJax itself, not just mathjax-node

I think the risk is greater because MathJax (on the client) lives in a much safer sandbox, in particular, regarding the file-system. I also think people are generally not aware of the fact that mathjax-node uses jsdom (and thus not awareness of its risks) and thus will be more careless.

**Comment by dpvc** [comment]
> I was thinking of a web service that allows users to send a configuration as well (e.g., to handle different math delimiters).

Since the new `main.js` only handles one equation at a time, and these are not delimited, there is no reason to set the delimiters (and if you do, it will screw up `mathjax-node`).  Any handling of delimiters is now supposed to be done by the calling application, so is not up to `mathjax-node`.

Also, I would not expect such a service to pass an unfiltered configuration into MathJax, but would take the configuration given to the service and make a new configuration for MathJax from that.  Allowing arbitrary configuration parameters would allow the client to completely disable MathJax (regardless of whether we allow external resources).  Certainly I would not expect to allow arbitrary values in the extension arrays in such a situation.  Moreover, in order to allow such reconfiguration (that included extensions) you would need to start a new copy of MathJax each time the configuration changed, which would be pretty inefficient, and is not well supported by `mathjax-node` currently.

> That was what I was thinking about. Maybe that's too simplistic.

Better than nothing, I guess, though I think your problematic use-case is a stretch.

> I think the risk is greater because MathJax (on the client) lives in a much safer sandbox

If someone could hijack MathJax to execute code in the browser, that would be a very serious issue indeed.  This would allow the page to submit forms, for example, or change cookies, or investigate the local storage or window history or any number of other nefarious things (most of which are an issue in `mathjax-node`).  The fact that it could not access your filling system is good, but not the only security issue.  Plus people who run web services know they are running a service that accepts (possibly evil) data from the world, and should know a little something about the security of the tools they use; general users of browsers certainly are not going to aware of these issues.
