### ISSUE TITLE
Add a promise-based API

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#297]
See also https://phabricator.wikimedia.org/T155201.

**Comment by pkra** [comment]
Cf. also this wrapper https://github.com/mathjax/MathJax-node/issues/251#issuecomment-231700042

**Comment by dpvc** [comment]
I'm not sure exactly what is being requested (I did read the link).  I think your suggestion of doing a blank typeset is the right one for finding out when MathJax is ready (though I'm not sure why that is necessary, since the typeset commands will queue even as MathJax is starting up).

It certainly doesn't do anything about the startup time (which no one has answered in that discussion).  The startup time is long because all of MathJax has to load, as well as jsdom and all its parts.  Those are both big packages, and compiling them takes a while.  That's why starting the MathJax-node library and having it serve multiple equations is a more efficient way to go.

I'm also not sure why promises are needed for a command-line tool (since we already have command line too without it).  Perhaps they are planning to pipe input/output to one that handles multiple equations (something like the `tex2svg-filter` example in the bin directory)?  But I don't see why that is any better than linking to the MathJax-node library directly and calling it multiple times.

So I'm a little confused by what is being requested.

**Comment by dpvc** [comment]
In any case, here is an example that uses your idea to implement a promise-based interface.  You call `StartJM()` to get a promise that is satisfied when MathJax starts up (and returns errors if it fails to start up).  In it's `then` call, you can call `Typeset(data)` to typeset the five data objects and get a promise that is satisfied when the typeset is complete (and that fails if there are errors).

Technically, you just need the `Typeset()` function, since the first one will not succeed until MathJax starts, but `StartMJ()` is syntactic sugar to give what the discussion above seemed to ask for.

```
#! /usr/bin/env node

var mathjax = require(".");
mathjax.config({displayErrors:false});

function Typeset(data) {
  return new Promise(function (ok, fail) {
    mathjax.typeset(data, function(data) {
      if (data.errors) fail(data.errors);
      else ok(data);
    });
  });
}

function StartMJ() {return Typeset({math:''})}

StartMJ().catch(errors => console.log("Startup error:",errors)).then(function () {

  Typeset({math:'x+1', svg:true})
    .then(data => console.log(data.svg))
    .catch(errors => console.log("Errors:",errors));

});
```

**Comment by pkra** [comment]
ping @physikerwelt @mobrovac

**Comment by pkra** [comment]
I'd like to propose to make mathjax-node both promise and callback compatible.

A minimal change might be to keep the current `typeset` as `cbTypeset` and then add 

```

exports.typeset = function (data, cb) {
    if (cb) cbTypeset(data, cb);
    else return new Promise(function (resolve, reject) {
        cbTypeset(data, function (output, input) {
            if (output.errors) reject(output.errors);
            else resolve(output, input);
        });
    });
};
```

**Comment by dpvc** [comment]
That seems reasonable, and should work.

**Comment by pkra** [comment]
Ok'ed per F2F. Wait until 1.2.0.

**Comment by pkra** [comment]
Fixed in `develop`
