### ISSUE TITLE
[TeX input] autoload does not load the color extension [was: \definecolor does not work]

### ISSUE THREAD

**Issue by physikerwelt** [mathjax/MathJax-node#307]
I'm not sure if that's a MathJax or a Mathjax-node bug. But it seems that \definecolor has stopped working

see
#306
for a test case

**Comment by pkra** [comment]
This is due to #175. MathJax-node was loading the autoload extension which in turn loads the color extension. Since color is the only extension loaded by autoload that changes core behavior (the others only add features), this was deemed inconsistent with core MathJax.

You can manually load the color extension to re-enable it. 

Your test exposes a drawback of the resolution of #175: specifying the autoload extension manually now fails to load the color extension.

It might be best after all if we didn't load autoload in mathjax-node but the specific extensions.

**Comment by physikerwelt** [comment]
> You can manually load the color extension to re-enable it.

Yes! Thank worked. @pkra thank you for your outstanding support.

From my point of wie the issue can be closed.

**Comment by pkra** [comment]
Glad to hear it worked. 

I'd like to leave it open to check whether we want to revisit the autoloading behavior.

**Comment by physikerwelt** [comment]
It's not a new bug though
https://github.com/wikimedia/MathJax-node/pull/7/commits/241703c70d32dd82a0288dff1ba7ea1c42f8c52e

**Comment by pkra** [comment]
Simple fix: expand the check at https://github.com/mathjax/MathJax-node/blob/master/lib/main.js#L425 to `autoload-all.js`
