### ISSUE TITLE
update default fontURL

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#323]
https://github.com/mathjax/MathJax-node/blob/master/lib/main.js#L41

**Comment by pkra** [comment]
While writing a test, I realized the fontURL cannot be reconfigured. I'll add that to a PR.

**Comment by dpvc** [comment]
There are many things that can't be reconfigured.  The configuration must be done before any typesetting is done, and can't be changed.  If you need to change configurations, you must call `mjAPI.start()` again in order to restart MathJax.

**Comment by pkra** [comment]
I'm fine moving this to `start()` but it currently won't re-configure this either since `CHTMLSTYLES` is generated at the first startup.

**Comment by dpvc** [comment]
It is set within the `AuthorInit` function so should be reset when the new MathJax starts up.  Unfortunately, calling `start()` with the callback of a previous `typeset()` call messes up the synchronization, and the new MathJax hasn't started up yet when the next `typeset()` is run, so you get the old one again.

You can get around this in one of two ways:  either enclose your `start()` and `typeset()` calls in a `setTimeout()` call, so that they will run *after* the callback completes; or modify `main.js` as follows:

* Swap [lines 776 and 777](https://github.com/mathjax/MathJax-node/blob/master/lib/main.js#L776-L777)

* Replace [line 778](https://github.com/mathjax/MathJax-node/blob/master/lib/main.js#L778) by
    
        if (serverState === STATE.READY) StartQueue();

* Move [line 812](https://github.com/mathjax/MathJax-node/blob/master/lib/main.js#L812) to after the close brace at line 813.

That will allow you to call `start()` from within a `typeset()` callback.

I've made a branch (`issue323`) that includes these changes.
