### ISSUE TITLE
jsdom 10 compatibility

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#325]
jsdom 10 has changed its API.

It's also node 6+ only now.

**Comment by pkra** [comment]
@dpvc any chance you can look into this some time?

**Comment by dpvc** [comment]
I've submitted a PR for this.

**Comment by dpvc** [comment]
Looks like I need to fix some tests first.  Sorry about that.  I'm stuck on one with mglyph, since jsdom10 doesn't have the same flexibility about blocking the loading of items as version 9 did (you could allow scripts, but not images, and that can no longer be done, apparently).  So I need to override mode of MathJax to get mglyph to work properly with jsdom 10.

**Comment by pkra** [comment]
:heart: Thanks, Davide.

**Comment by pkra** [comment]
jsdom 10+ is node6+ only, so this should cause a major version jump, I think.

**Comment by pkra** [comment]
Oh, and travis needs to be restricted as node4 and 5 probably always fail.

**Comment by dpvc** [comment]
> Oh, and travis needs to be restricted as node4 and 5 probably always fail.

I don't know how travis is set up or configured.  Can you point me to the right place to do that?

**Comment by pkra** [comment]
Sure! It's https://github.com/mathjax/MathJax-node/blob/master/.travis.yml#L3-L4

**Comment by dpvc** [comment]
Thanks.  I didn't see it because it was a dot file, and I didn't think to look for that (am used to .json files now)

**Comment by dpvc** [comment]
OK, the tests all pass now.  I think it is ready to go.

**Comment by dpvc** [comment]
I've updated the version number and added the node6 engine dependency.

**Comment by dpvc** [comment]
==> Merged
