### ISSUE TITLE
[SVG output] improve string-width detection for text elements

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#368]
#358 introduced detection for full-width forms. A more advanced approach might use [string-width](https://github.com/sindresorhus/string-width) which handles more cases such as (some) combining characters.

Note it's not perfect and won't help with all combining characters, in part due to natural ambiguities ("can we assume the user's system will combine the characters?", see also https://github.com/sindresorhus/string-width/issues/2, https://github.com/sindresorhus/string-width/issues/4).

However, we're currently split up strings in text elements anyway, so we would need to make sure all characters end up in the same text element.

**Comment by codificador-nocturno** [comment]
Hi!

I'm not sure if this has to do with this issue, so I'd prefer to ask instead of creating a new one.

For an asciimath text like this:
los números `NN` naturales

We are getting the N cropped, like this:

![screen shot 2018-06-07 at 12 40 55](https://user-images.githubusercontent.com/17958346/41116508-21529516-6a50-11e8-83f2-d40d9ae1d1a6.png)

What could be happening?

Thanks!

Tech details:
mathjax-node 2.1.1
nodejs 8
SVG output
Neo-Euler font
Chrome Browser
macOS High Sierra

**Comment by pkra** [comment]
Cleaning up my old issues.
