### ISSUE TITLE
[ANNOUNCEMENT] mathjax v3 in beta

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#375]
For those not following the mathjax-dev mailing list or the MathJax/MathJax repository, MathJax v3 is in alpha and currently resides at https://github.com/mathjax/mathjax-v3.

It's a re-write of (most of) MathJax and supports NodeJS out of the box, thus (eventually) this code base will become obsolete.

**Comment by CalebKester** [comment]
Is there any sort of timeline for this?

**Comment by Pomax** [comment]
In that case, can the README be updated to mention that this repository is deprecated and will be archived at some point in the future, with links to the new preferred method, and a list of equivalent mathjax3 examples for things that currently require mathjax-node?

"Package X can now do this" is effectively the worst possible transition documentation =)

**Comment by dpvc** [comment]
The alpha release is still very preliminary and there is much still to do.  We are hoping for a beta release second quarter this year.  That will be a release intended for public consumption, and will have appropriate usage documentation at that time.

**Comment by saivan** [comment]
If we are using this, is it an appropriate time to migrate to v3, or is it still too unstable at the moment?

**Comment by pkra** [comment]
Now in beta - https://www.mathjax.org/MathJax-v3-beta/

**Comment by Pomax** [comment]
Nice! Can the README.md be updated with a new section up top that explains that MathJax v3 is in beta and will deprecate mathjax-node once stable, with the request for people to try to use the MathJax v3 beta instead, along with code examples of how they can use MathJax v3 to do what they were using mathjax-node for before?

**Comment by dpvc** [comment]
The MathJax v3 beta [README](https://github.com/mathjax/mathjax-v3/blob/beta/README.md) includes documentation on getting and using MathJax v3 beta, and there are examples in the [mj3-demos-node](https://github.com/mathjax/mj3-demos-node) repository for using MathJax v3 in node.  More documentation and demos are found in the [mj3-demos](https://github.com/mathjax/mj3-demos) repository, but these are mostly for web-page use; it does list most of the options for the TeX input and CHTML output components, however.  Version 3 does not yet include SVG output, but that is coming.  More documentation is needed, of course, but this is a start.

**Comment by Pomax** [comment]
Hurray for docs in the mj3 repositories, but I'd still strongly request a change to _this repository_ where the README.md is updated to point people in the right direction. If there are plenty of examples already available in the mj3 README.md and in its repositories, then linking to those is of course fine, but it's important to give people that "hey this project will go out of maintenance soon in favour of mathjax 3, which can run in Node as well as the browser. Go [here]() to find out all about it, and [here]() to see examples of how to use it" heads up as the very first thing they see when they find their way to this repo =)

**Comment by dpvc** [comment]
I wasn't suggesting that there shouldn't be those changes, only trying to point you to the existing documentation in case you were not aware of it.  Since many people are using mathjax-node to generate SVG images, and MathJax v3 doesn't yet produce those, it may be too early to suggest people change to v3 just yet.  Also, I'm also not sure that "this project will go out of maintenance soon" is an accurate statement (but I guess that depends partly on people's definition of "soon").

**Comment by Pomax** [comment]
fair point, "soon" is super relative (sublime text's idea of soon was about 5 years =P)

Is SVG export on the mathjax 3 roadmap, or not something that will land until some 3.1 or later? If it's on the roadmap for 3, any rough timeline estimate for how long that might take, and (a) link(s) to the related issue(s)?

**Comment by dpvc** [comment]
I am hoping that SVG will be included in the 3.0.0 release, and I' hoping to get the SVG implementation under way next month.  Much of the CommonHTML framework can be reused for that, so I think it should more relatively quickly.  There are no issues currently open for SVG.

**Comment by physikerwelt** [comment]
It seems that MathJax 3 is out. Do we still need mathjax-node or is it advised to use matjax directly from npm. http://docs.mathjax.org/en/latest/api/ was not really helpful;-)

**Comment by dpvc** [comment]
> Do we still need mathjax-node or is it advised to use mathjax directly from npm

It is up to you whether you make the change to v3.  I suspect the current lack of line-breaking support will be a deal-breaker for you for now.  That is one of the high-priority features to be worked on next.  Also, v3 currently only has support for the MathJax TeX font, not STIX fonts, so that may also prevent you from using it.  That is also a high priority item for a future release.

It is true that the documentation is not yet in place for the direct calls to MathJax 3, but there are several approaches to using MathJax 3 from node, and one uses essentially the same interface as for web pages, so the much of the web page documentation applies.  There is also the [MathJax node demos](https://github.com/mathjax/MathJax-demos-node#mathjax-demos-node) which illustrate three different approaches to using MathJax v3 from node.

**Comment by RambabuPatina** [comment]
Hi Team, Do you have any plans to release soon with mathjax v3? please let us know.

**Comment by pkra** [comment]
v3 came out in 2020 -- see https://www.mathjax.org/news.  

v4 is currently in alpha https://github.com/mathjax/MathJax/releases/ 

If you haven't moved from mathjax-node to something from [MathJax-demos-node](https://github.com/mathjax/MathJax-demos-node/) it's probably time.

**Comment by RambabuPatina** [comment]
Thanks @pkra for your swift response. We are using mathjax-node@2.1.1 in our application. 
Could you please provide guidelines if any to migrate from mathjax-node to mathjax v3.

**Comment by pkra** [comment]
I don't work for MathJax (anymore) but I'm available for consulting; feel free to ping me by email if that's what you're looking for.
