### ISSUE TITLE
[TeX input, MathML output] \pi not becoming π

### ISSUE THREAD

**Issue by Sora2455** [mathjax/MathJax-node#380]
I apologise if this is actually a MathJax issue, but I thought I'd ask here first.

The TeX for Euler's identity is `e^{i\pi}+1=0`. When I enter this into http://www.wiris.com/editor/demo/en/mathml-latex, I get the MathML I was expecting:
`<math xmlns="http://www.w3.org/1998/Math/MathML">
    <msup>
        <mi>e</mi>
        <mrow>
            <mi>i</mi>
            <mi>&#x3C0;</mi>
        </mrow>
    </msup>
    <mo>+</mo>
    <mn>1</mn>
    <mo>=</mo>
    <mn>0</mn>
</math>`

Here, \pi was converted into `&#x3C0;`, the HTML character encoding for π.

When I enter this into MathJax-Node, however, I instead get:
`<math xmlns="http://www.w3.org/1998/Math/MathML" display="block" alttext="e^{ipi}+1=0"> 
    <msup>
        <mi>e</mi>
        <mrow class="MJX-TeXAtom-ORD">
            <mi>i</mi>
            <mi>p</mi>
            <mi>i</mi>
        </mrow>
    </msup>
    <mo>+</mo>
    <mn>1</mn>
    <mo>=</mo>
    <mn>0</mn>
</math>`

Here, \pi has been converted into p * i.

π is a really common maths symbol - can anybody tell me why MathJax doesn't seem to recognise it?

**Comment by dpvc** [comment]
If you are entering `e^{i\pi}+1=0` in a string in your javascript, you will need to double the backslash, since in javascript string literals, the backslash is a special character.  I.e., 

```
var math  = 'e^{i\\pi}+1=0';
```
not
```
var math  = 'e^{i\pi}+1=0';
```

If you don't double it, then in this case, `\p` will just mean `p`, so it is as though the math is just `e^{ipi}+1=0`, which would produce the result that you are seeing.  But things like `\n` and `\t` have special meaning in strings (these are newline and tab, respectively).  You need to use `\\` to get a literal backslash in your string.  So this is really a javascript issue, rather than a MathJax one.

**Comment by Sora2455** [comment]
...

Opps.

Sorry for the confusion (and I thought I'm good at JavaScript!).

**Comment by dpvc** [comment]
No problem.  It is easy to forget that when you are looking at TeX code (I do it all the time myself).
