### ISSUE TITLE
sanitize user config broke ability to extend TeX.extensions

### ISSUE THREAD

**Issue by simonista** [mathjax/MathJax-node#410]
https://github.com/mathjax/MathJax-node/issues/309 broke the ability to extend TeX.extensions, which we use to load the "color.js" extension.

Specifically, this configuration broke from 1.0.2 to 1.0.3:

```
mj.config({
  MathJax: {
    TeX: {
      extensions: ["color.js"]
    }
  }
});
```

**Comment by pkra** [comment]
It sounds like you're looking for the `extensions` key in the `config`' options, https://github.com/mathjax/MathJax-node#configoptions. It expects a comma separated string of paths, e.g., 

```
mj.config({
    extensions: "TeX/color"
});
```

See also https://github.com/mathjax/MathJax-node/issues/401 for a related minor bug that will be fixed in the next release (but has a workaround).

**Comment by simonista** [comment]
Ah, thanks!
