### ISSUE TITLE
File load err: file://svg/jax.js error thrown at times

### ISSUE THREAD

**Issue by einsteinreloaded** [mathjax/MathJax-node#422]
![image](https://user-images.githubusercontent.com/7992580/43382548-b4912ea4-93f5-11e8-98c0-41d7134aeb41.png)

**Comment by dpvc** [comment]
The error message is not enough to give you any help.  Can you provide a minimal example code that illustrates the problem you are having?

One possibility is that you don't have mathjax installed properly.  Did you check that the files like `file:///app/node_modules/mathjax/unpacked/jax/output/SVG.jax.js` actually exist?  Is the path correct?  (I.e., are you working in the top-level directory called `app`?)

**Comment by einsteinreloaded** [comment]
This is occurring once in a while not always.

**Comment by dpvc** [comment]
> This is occurring once in a while not always.

I understand that, but without a code sample to work with, there is nothing we can do to help.  We have no idea what your setup is, how you are calling mathjax-node, or what sort of timing issues might be causing the problem intermittently.

The fact that it is not always occurring suggests that there is a race condition somewhere in your app (so that sometimes something is not set up in time for mathjax-node to load its files properly).  Those are notoriously difficulty to diagnose.  Certainly we have no hope if doing so without knowing the details of how your app works.

I'm sorry, but there isn't much else we can do at this point.

**Comment by einsteinreloaded** [comment]
`router.post '/equationhtml', (req, res)->
	try 
		mathjax.start();
		yourMath = req.body.eqntex
		mathjax.typeset({ 
				math: yourMath,
				format: "inline-TeX", 
				html: true
			},
			(data) -> 
				res.send data
		);
	catch err
		winston.info(err)`

I am using this code in my router file. i have tried putting them inside try and catch as you can see but still the error doesn't get caught in this try catch.

**Comment by dpvc** [comment]
Try removing the `mathjax.start()` call.  It is not needed, and causes MathJax to be reloaded for every request.  That means it has to load all its files again, which seems to be where you are running into troubles.

**Comment by einsteinreloaded** [comment]
@dpvc I missed out on that. Thank you I will implement this fix and closing this issue will reopen if still exists
