### ISSUE TITLE
width of svg is too small

### ISSUE THREAD

**Issue by symlons** [mathjax/MathJax-node#473]
the width of the generated SVG is sometimes too small eg. in the combination of the characters it is particularly noticeable
with the combination sdf:
<img width="351" alt="Screen Shot 2021-07-20 at 4 51 44 PM" src="https://user-images.githubusercontent.com/63979635/126346133-51d101e7-73c8-4845-931c-eac7d192e463.png">

**Comment by dpvc** [comment]
If you are viewing this in a browser, because the width and height are given in `ex` units, at some zoom levels the rounding of those dimension to actual pixel values sometimes can cause the size to be too small.  Does the effect change if you zoom to different sizes?  (I see this effect in Firefox only at certain zoom levels.)

One option would be to add `style="overflow: visible"` to the SVG element itself, as that will allow the full character to be displayed even if the box size isn't quite right.

You may also consider using MathJax v3 rather than `mathjax-node`, which is based on version 2.  Version 3 can be run in node directly, rather than needing the rather fragile framework used in `mathjax-node`.

**Comment by symlons** [comment]
Thanks for the tip!
setting overflow to visibile improved the situation in Chrome but in Safari the issue is still noticeable.
