### ISSUE TITLE
width input option

### ISSUE THREAD

**Issue by gbala2412** [mathjax/MathJax-node#62]
I want to convert a math to png/svg with linebreak option,  width of the math should be 600px . I don't know how to achieve this.
If I want reduce/increase the font size where I've to mention it? 
If you could explain all the options in the README file which helps a lot for all.

Commands and output

1.   node bin/mml2png --linebreaks --width=6000 -- ex=2 '&lt;math>&lt;/math>' > width600_ex2.png
2.   node bin/mml2png --linebreaks --width=6000 -- ex=20 '&lt;math>&lt;/math>' > width600_ex20.png
3.   node bin/mml2png --linebreaks --width=1000 -- ex=2 '&lt;math>&lt;/math>' > width100_ex2.png 
4.   node bin/mml2pbg --linebreaks --width=1000 -- ex=20 '&lt;math>&lt;/math>' > width600_ex20.png

![w1k_ex2](https://cloud.githubusercontent.com/assets/488029/5472116/1f918b3e-8623-11e4-9128-5d3060f0f64a.png)
![w1k_ex20](https://cloud.githubusercontent.com/assets/488029/5472124/352bab00-8623-11e4-84a6-b8a5ca81662e.png)
![w6k_ex2](https://cloud.githubusercontent.com/assets/488029/5472137/5738833a-8623-11e4-98ab-9b8d3a496fab.png)
![w6k_ex20](https://cloud.githubusercontent.com/assets/488029/5472130/4332bc5c-8623-11e4-8658-2163e5db184d.png)

**Comment by pkra** [comment]
This problem seems to have shifted with MathJax v2.5-final. The overlap issue seems to have been solved but linebreaking fails. Will investigate further.

**Comment by dpvc** [comment]
There are several things going on, here.  One is a bug in MathJax-node where the line breaking width was not being passed to MathJax properly.  (The SVG output jax computes sizes in units of 1/1000 em, but MathJax-node was passing pixels instead.)

The other issue is that the `--width` parameter is given in units of ex not px, so `--width=6000` means 6000ex, so no line breaking would be needed in that case (but the missing factor of 1000 internally messed that up).

A value of `--ex=2` means that the ex-hight is 2 pixels, which is probably not a very good idea, and it is the reason why the fractions and subscripts are so large.  That is because there is a minimum size used when the font size changes (for scripts and fractions), but it is larger than your original 2px ex-height, and so the subscripts get *larger*.

I'm not certain that you posted the correct picture for your second example, as it is the same as your first, but it should be the same as the fourth.  But it doesn't really matter, as I have a fix for the line breaking width problem in the `issue62` branch of MathJax-node.

Since `--ex` is the ex-height in pixels, and `--width` is the line-breaking with in ex, in order to get a 600px image, you would need the value of `--ex` times the value of `--width` to be 600.  The default values are `--ex=6` and `--width=100`, so that is already 600px, so you should be able to go with the default.

If you want the actual size of a pixel in the image to be a pixel in the MathML, then you need to use `--dpi` set to 16 times the `--ex` value.  The `issue62` branch changes the default of `--dpi` from 144 to 0, where 0 means to calculate the dpi value to be the ex-height times 16.  So in that branch, you should be able to leave off all three parameters.

**Comment by pkra** [comment]
Fixed in 0.3

**Comment by gbala2412** [comment]
Thank you very much!!!!!

**Comment by gbala2412** [comment]
mml2png works fine but mml2svg font size not rendering as per the ex value. Attached sample html, png and svg files. 

https://drive.google.com/file/d/0ByIDsiVMQVJRallLSHp3cnhMV1k/view?usp=sharing

**Comment by dpvc** [comment]
The size of the SVG file is given in units of `ex`, so its rendering will depend on the font size of the page in which it appears.  The `ex` value you give is supposed to tell MathJax-node what that size is going to be (MathJax doesn't force that size).  The `ex` value is used to determine the dpi for png output, and to convert measurements given in units of `px`, `mm`, `in` and other such units to the proper internal SVG units.  But it is not used to force an absolute size for the final SVG element.  That size is determined by the font size of the surrounding text.

So in your example, I would expect all the SVG files to be the same size (because the surrounding text is the same throughout).  That is what I see.

Also, in the future, you should open a new issue if you are reporting a new problem (which this is).

**Comment by gbala2412** [comment]
Thanks for the reply.
