### ISSUE TITLE
Feature request: `mjfragment`

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#69]
It would be nice to have an API for processing content fragments.

Some potential features

* save generated styles separately
* store paths externally ([needs a small polyfill in IE](http://css-tricks.com/svg-use-external-source/))
* handle non-HTML situations like markdown

Besides keeping the page itself cleaner, this allows for more efficient delivery, especially when processing multiple files (e.g., a statically re-generated site, ebooks) and also improves processing of non-HTML such as markdown files (in particular with YAML front matter).

**Comment by pkra** [comment]
Sorry hit save too early, just as I was re-writing the OP. It's been updated.

**Comment by dpvc** [comment]
I'm not sure I understand the request.  The `mj-page.js` file already takes an HTML fragment (it doesn't have to be a full page).  Perhaps you are asking for new commands in `bin` to take a fragment rather than a full HTML page?  It turns out that this is already possible by simply passing just an HTML fragment rather than a whole page to `bin/page2*`.  E.g.,

    echo "This is some math: $x+1$" | bin/page2mml

You do get a complete page back, but that is due to how `bin/page2mml` works, not `mj-page.js`.  One could certainly make a tool that separates the styles, the svg paths and the svg output, if that were desired.

So I'm really not quite sure what is being requested.

**Comment by pkra** [comment]
> I'm not sure I understand the request. 

I don't fully either ;-) More seriously, I'm not yet sure what I'm after and if it should be part of MathJax-node. I recorded this issue primarily so that I wouldn't forget. (I ended up writing workarounds for the project that brought this up so this is not at all urgent.)

The problem I ran into with mj-page is that it modifies the page much like MathJax does (injecting styles, SVG paths etc). For use cases like processing ebooks, generic XML files, or markdown+yaml this is not ideal.

For example, processing an ebook (epub3, kf8), I'd want to collect up the css and the paths in one file each, across all xhtml files in the book (and then reference paths externally). A similar situation arises with XML files (e.g., rss, atom, but also JATS/BITS), where HTML/CSS additions would be invalid, or with markdown files with yaml preambles (e.g., for generators like Jekyll).

So I was thinking that mathjax-node could provide an API similar to `mj-page` but that would modify the fragment/page as little as possible, i.e., only touch the equational content (in a minimal fashion), provide a way to collect up data such as SVG paths and CSS so that they can passed on for further processing, maybe even handle several fragments (e.g., automatic equation labels).

**Comment by dpvc** [comment]
I think `mj-single` may be the one you want to use in this case, as it allows you to maintain state across the equations, keeping a common cache of paths, and maintaining the numbering sequence.  Since you can take the equations from several files, this should allow you to keep the paths from multiple pages in a single file.  The CSS is constant (I'm pretty sure), so you should be able to capture that once and not worry about it any more.

Of course, the downside here is that you have to locate the equations yourself.  This can be trickier than you might think.

**Comment by pkra** [comment]
Similarly to #119, I'm thinking we should build a nice collection of samples.

**Comment by pkra** [comment]
Closed in favor of #206
